---
# tasks file for configsvr

- name: "Setting MONGODB_URI variable"
  template:
    src: mongodb.sh.j2
    dest: /etc/profile.d/mongodb.sh

- name: "Configuring server to be configsvr"
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    mode: '0644'
  notify: 
  - restart-mongodb

#- name: "Adding MongoDB Exporter user"
#  mongodb_user:
#    login_host: "{{ ansible_eth1.ipv4.address }}"
#    login_port: '27019'
#    database: admin
#    name: mongodb-exporter
#    roles: clusterMonitor,read
#    state: present
#    password: qwe123qwe
