---
# tasks file for prometheus_exporters

- name: "Copying MongoDB exporters"
  copy:
    src: mongodb_exporter.tar.gz
    dest: /tmp
  
- name: "Copying Node exporters"
  copy:
    src: node_exporter.tar.gz
    dest: /tmp


- name: "Extracting MongoDB Exporter"
  unarchive:
    src: /tmp/mongodb_exporter.tar.gz
    dest: /usr/local/sbin/
    remote_src: yes

- name: "Extracting Node Exporter"
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes
    mode: "0774"
    owner: root
    group: root

- name: "Copying Node Exporter"
  copy:
    src: /tmp/node_exporter-0.18.1.linux-amd64/node_exporter
    dest: /usr/local/sbin/
    remote_src: yes
    mode: "0774"
    owner: root
    group: root


- name: "Creating Node Exporter SystemD service"
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: "Creating MongoDB Exporter SystemD service"
  template:
    src: mongodb_exporter.service.j2
    dest: /etc/systemd/system/mongodb_exporter.service

- name: "Enable Node and MongoDB Exporter Services"
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
  - mongodb_exporter
  - node_exporter
