---
# tasks file for mongodb
- name: "Adding MongoDB 4.4 CentOS Repository"
  when: ansible_facts['distribution'] == 'CentOS'
  yum_repository:
    name: mongodb-org-4.4
    description: MongoDB version 4.4
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/ 
    enabled: yes
    gpgcheck: 1
    gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc

- name: "Adding MongoDB 4.4 Debian 9 Repository"
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == 9
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.4 main
    state: present  
    cache_update: yes

- name: "Adding MongoDB 4.4 Debian 10 Repository"
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == 10
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main
    state: present  
    cache_update: yes

- name: "Installing MongoDB 4.4"
  package:
    name: ['mongodb-org','python3-pymongo']
    state: present
