---
# tasks file for mongodb
- name: "Adding MongoDB 4.2 CentOS Repository"
  when: ansible_facts['distribution'] == 'CentOS'
  yum_repository:
    name: mongodb-org-4.2
    description: MongoDB version 4.2
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/ 
    enabled: yes
    gpgcheck: 1
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc

- name: "Adding MongoDB 4.2 Debian 9 Repository"
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == 9
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 main
    state: present  
    cache_update: yes

- name: "Adding MongoDB 4.2 Debian 10 Repository"
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == 10
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main
    state: present  
    cache_update: yes

- name: "Installing MongoDB 4.2"
  package:
    name: ['mongodb-org','python36-pymongo']
    state: present
