---
# tasks file for shard
- name: "Copy sharding configuration file"
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify: restart-mongodb

- name: Hostname
  debug:
    msg: Hostname {{ ansible_facts['nodename'][:3]}}
