---
# tasks file for prereq

- name: "Setting hosts file"
  copy:
    src: hosts
    dest: /etc/hosts

- name: "Installing CentOS EPEL-RELEASE package "
  when: ansible_facts['distribution'] == 'CentOS'
  dnf:
    name: epel-release
    state: present


- name: "Disabling SELinux"
  when: ansible_facts['distribution'] == 'CentOS'
  selinux:
    state: disabled

- name: "Disable Firewalld"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: "Installing extra packages"
  package:
    name: ['vim','chrony']
    state: present


