---
# tasks file for docker


- name: Installing Docker CentOS repository
  when: ansible_facts['distribution'] == 'CentOS'
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Installing Docker packages
  when: ansible_facts['distribution'] == 'CentOS'
  dnf:
    name: ['docker-ce','docker-ce-cli','containerd.io']
    state: present

- name: Upgrade libseccomp
  when: ansible_facts['distribution'] == 'CentOS'
  dnf:
    name: 'libseccomp'
    state: latest

- name: Enabling SystemD Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  
